### ISSUE TITLE
Type piracy of complex conversion of UniformScaling

### ISSUE THREAD

**Issue by andreasvarga** [JuliaTesting/Aqua.jl#261]
I am trying to define in my package [MatrixEquations](https://github.com/andreasvarga/MatrixEquations.jl) a simple conversion to complex type of an arbirary `UniformScaling`. For my first trial with

`Base.complex(A::UniformScaling) = complex(A.λ)*I`

Aqua complains of possible type piracy. The same occurs for two other definitions 

```
Base.complex(A::UniformScaling{T}) where {T<:Real} = Complex{T}(A.λ)*I

Base.complex(A::UniformScaling) = Complex{eltype(A)}(A.λ)*I

```
I wonder what is the cause of this, because all three definitions work well for my purposes.

**Comment by hyrodium** [comment]
If you would like to avoid type piracies, your package needs to own function or argument type.
The definition `Base.complex(A::UniformScaling) = complex(A.λ)*I` looks correct, so that should be defined in LinearAlgebra.jl.

The following articles would be useful to learn type piracies.

* https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy
* https://juliatesting.github.io/Aqua.jl/stable/piracies/
* https://discourse.julialang.org/t/how-bad-is-type-piracy-actually/37913

**Comment by lgoettgens** [comment]
Thanks for the explanation @hyrodium!

**Comment by andreasvarga** [comment]
Thanks for the explanation. I fixed the type piracy issue by defining my own function `tocomplex` as follows:

```
tocomplex(A::LinearAlgebra.UniformScaling) = complex(A.λ)*I
tocomplex(A::AbstractArray) = complex(A)
tocomplex(A::Number) = complex(A)
```
