### ISSUE TITLE
Possible Check: Any calls of `rand` or `sample` include an RNG

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaTesting/Aqua.jl#66]
Unsure if this aligns with the kind of thing Aqua is supposed to do, but checking that any calls to `rand` or `sample` in the package include an RNG argument would be extremely useful to avoid having to chase these down when I forget to add them.

**Comment by tkf** [comment]
Thanks for your interest in improving Aqua. But I think it's beyond Aqua's scope since it'd require serious code analysis. Instead, I think it'd be much easier to use the method Jan Weidner suggested: [Disable global RNG - General Usage - JuliaLang](https://discourse.julialang.org/t/disable-global-rng/20690/7)

In fact, I think it'd be a good thin package to automate his idea:

```julia
module ExplicitRandom
import Random
rand(rng::Random.AbstractRNG, args...) = Random.rand(args..)
shuffle(rng::Random.AbstractRNG, args...) = Random.shuffle(args..)
# ...and so on
end
```

**Comment by ParadaCarleton** [comment]
Thank you!
